node_js:
- '0.10'
language: node_js
install:
- npm install -g gulp
- npm install
script:
- gulp travis

deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "viper-test-pages"
  skip_cleanup: true
  local_dir: dist
